### ISSUE TITLE
Cannot build mongodb driver in VS 2015

### ISSUE THREAD

**Issue by arietto** [treefrogframework/treefrog-framework#86]
Hello! I can't build treefrog 1.12 (official release) using VS 2015 x86 command prompt and Qt 5.6 (5.7 also failed).
It complains about failed mongodb driver compilation. Is it possible to switch off mongo db building?
I use PostgreSQL. Have you ever tested this framework with VS 2015 and/or latest Qt 5.7?

**Comment by treefrogframework** [comment]
I fixed compilation error of mongodb driver.
I will release in next Qt version, v5.7.1.

**Comment by treefrogframework** [comment]
Can build TreeFrog v1.13.0 on Qt5.6.2 and VS 2015.

**Comment by treefrogframework** [comment]
fix errors.
08827c7885cc2adc551c5d84a342902cf3322405
I will release in next version.

**Comment by treefrogframework** [comment]
Fixed in version 1.15.
